name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache npm
      uses: actions/cache@v2
      env:
        cache-name: cache-npm
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-${{ env.cache-name }}-
          ${{ runner.os }}-npm-
          ${{ runner.os }}-
    - name: Setup the correct Node version using nvm
      shell: bash -l {0}
      run: nvm install
    - run: npm ci
    - run: npm test
      env:
        DISPLAY: ':99'
        BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
        BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
